# Generated by Django 5.2.7 on 2025-10-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, default='', help_text='Phone number in format: +256XXXXXXXXX', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('household', 'Household'), ('business', 'Business'), ('collector', 'Collector'), ('recycler', 'Recycler'), ('quick_access', 'Quick Access')], default='household', max_length=20),
        ),
    ]
