# Generated by Django 5.2.7 on 2025-10-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_wastelisting_waste_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastelisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Waste Listing', 'verbose_name_plural': 'Waste Listings'},
        ),
        migrations.AddField(
            model_name='wastelisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wastelisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
