# Generated by Django 5.2.7 on 2025-10-24 13:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_alter_wastelisting_options_wastelisting_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastelisting',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
